# docs/_config.yml
# =======================================
# Jupyter Book Configuration for ASC-bla
# =======================================

title: ASC-bla
author: A. Graf, S. Reicht, J. Teuschl
logo: ASC_Logo_transparent_300ppi_RGB.png
copyright: "2025, ASC-bla Team"

execute:
  execute_notebooks: "force"
  timeout: 300

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/Sreichtt/ASC-bla
  path_to_book: docs
  branch: main

html:
  use_issues_button: true        
  use_repository_button: true    
  favicon: ASC_Logo_transparent_300ppi_RGB.png

parse:
  myst_enable_extensions:
    - html_image
    - dollarmath
    - amsmath
    - linkify
    - colon_fence
  myst_dmath_double_inline: true
